# Use an official Python runtime as a parent image
FROM python:3

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed dependencies specified in requirements.txt
RUN pip install -r requirements_dash.txt

EXPOSE 8050

# Run the Python script when the container launches
CMD ["python", "visual.py"]